// yeh file sirf data rakhegi

import property1 from "../../../assets/Cards Img/property-01.jpg";
import property2 from "../../../assets/Cards Img/property-02.jpg";
import property3 from "../../../assets/Cards Img/property-03.jpg";
import property4 from "../../../assets/Cards Img/property-04.jpg";
import property5 from "../../../assets/Cards Img/property-05.jpg";

// NOTE: agar images kam hain to tum same image multiple jagah use kar sakte ho.
// bas id aur data unique hona chahiye.

const properties = [
  // ---------- Villas (4) ----------
  {
    id: 1,
    type: "VillaHouse",
    price: "$2,264,000",
    address: "18 New Street Miami, OR 97219",
    bedrooms: 4,
    bathrooms: 3,
    area: "125m²",
    floor: "25th",
    parking: "2 cars",
    image: property1,
  },
  {
    id: 2,
    type: "VillaHouse",
    price: "$1,180,000",
    address: "54 Mid Street Florida, OR 27001",
    bedrooms: 4,
    bathrooms: 4,
    area: "180m²",
    floor: "38th",
    parking: "2 cars",
    image: property2,
  },
  {
    id: 3,
    type: "VillaHouse",
    price: "$450,000",
    address: "26 Old Street Miami, OR 38540",
    bedrooms: 3,
    bathrooms: 2,
    area: "165m²",
    floor: "26th",
    parking: "3 cars",
    image: property3,
  },
  {
    id: 4,
    type: "VillaHouse",
    price: "$980,000",
    address: "77 Sunset Blvd LA, OR 45210",
    bedrooms: 5,
    bathrooms: 4,
    area: "210m²",
    floor: "12th",
    parking: "3 cars",
    image: property4,
  },

  // ---------- Apartments (5) ----------
  {
    id: 5,
    type: "Apartment",
    price: "$320,000",
    address: "12 New Street Miami, OR 12650",
    bedrooms: 2,
    bathrooms: 1,
    area: "95m²",
    floor: "10th",
    parking: "1 car",
    image: property5,
  },
  {
    id: 6,
    type: "Apartment",
    price: "$410,000",
    address: "44 Ocean Drive Miami, OR 32690",
    bedrooms: 3,
    bathrooms: 2,
    area: "120m²",
    floor: "15th",
    parking: "1 car",
    image: property1,
  },
  {
    id: 7,
    type: "Apartment",
    price: "$520,000",
    address: "88 City Street Portland, OR 56410",
    bedrooms: 4,
    bathrooms: 3,
    area: "135m²",
    floor: "20th",
    parking: "2 cars",
    image: property2,
  },
  {
    id: 8,
    type: "Apartment",
    price: "$615,000",
    address: "21 River Road Florida, OR 12678",
    bedrooms: 3,
    bathrooms: 2,
    area: "110m²",
    floor: "14th",
    parking: "1 car",
    image: property3,
  },
  {
    id: 9,
    type: "Apartment",
    price: "$720,000",
    address: "19 Green Lane Miami, OR 78540",
    bedrooms: 5,
    bathrooms: 3,
    area: "155m²",
    floor: "22nd",
    parking: "2 cars",
    image: property4,
  },

  // ---------- Penthouses (6) ----------
  {
    id: 10,
    type: "Penthouse",
    price: "$925,600",
    address: "34 Beach Street Miami, OR 42680",
    bedrooms: 5,
    bathrooms: 3,
    area: "165m²",
    floor: "26th",
    parking: "3 cars",
    image: property5,
  },
  {
    id: 11,
    type: "Penthouse",
    price: "$1,250,000",
    address: "99 Skyline Tower NY, OR 58910",
    bedrooms: 6,
    bathrooms: 4,
    area: "220m²",
    floor: "30th",
    parking: "3 cars",
    image: property1,
  },
  {
    id: 12,
    type: "Penthouse",
    price: "$1,050,000",
    address: "11 Bay Street Miami, OR 47850",
    bedrooms: 4,
    bathrooms: 3,
    area: "185m²",
    floor: "28th",
    parking: "2 cars",
    image: property2,
  },
  {
    id: 13,
    type: "Penthouse",
    price: "$1,400,000",
    address: "55 Ocean View Miami, OR 17850",
    bedrooms: 6,
    bathrooms: 4,
    area: "240m²",
    floor: "32nd",
    parking: "4 cars",
    image: property3,
  },
  {
    id: 14,
    type: "Penthouse",
    price: "$1,800,000",
    address: "88 Sky Tower Miami, OR 11220",
    bedrooms: 7,
    bathrooms: 5,
    area: "300m²",
    floor: "40th",
    parking: "4 cars",
    image: property4,
  },
  {
    id: 15,
    type: "Penthouse",
    price: "$2,000,000",
    address: "123 Palm Beach Road Miami, OR 90210",
    bedrooms: 8,
    bathrooms: 6,
    area: "350m²",
    floor: "45th",
    parking: "5 cars",
    image: property5,
  },
];

export default properties;
